from adafruit_pioasm import Program

NEXT = """    out pc, 5
"""

SRC = f"""
.program pt
.origin 0

main:
{NEXT}

public opL:
    set pins, 0
    set pindirs, 1
{NEXT}

public opH:
    set pins, 1
    set pindirs, 1
{NEXT}

public opz:
    nop
    set pindirs, 0
{NEXT}

public opDelay:
    out x, 32
delay:
    jmp x-- delay
{NEXT}

public opi:
    set pindirs, 0
    in pins, 1
{NEXT}
"""

OUTPUT = "pt1.py"


def public_labels_without_op_prefix(labels):
    return {
        name[2:] if name.startswith("op") else name: offset
        for name, offset in sorted(labels.items())
    }


def write_module(path, program):
    labels = public_labels_without_op_prefix(program.public_labels)
    opcodes = ", ".join(f"0x{opcode:04x}" for opcode in program.assembled)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by gen.py. Do not edit by hand.\n")
        f.write("import array\n\n")
        f.write(f"PROGRAM = array.array('H', [{opcodes}])\n")
        f.write(f"PUBLIC_LABELS = {labels!r}\n")
        f.write(f"PIO_KWARGS = {program.pio_kwargs!r}\n")


pt = Program(SRC)
write_module(OUTPUT, pt)
print(f"wrote {OUTPUT}")
