# Generated by gen.py. Do not edit by hand.
import array

PROGRAM = array.array('H', [0x60a5, 0xe000, 0xe081, 0x60a5, 0xe001, 0xe081, 0x60a5, 0xa042, 0xe080, 0x60a5, 0x6020, 0x004b, 0x60a5, 0xe080, 0x4001, 0x60a5])
PUBLIC_LABELS = {'Delay': 10, 'H': 4, 'L': 1, 'i': 13, 'z': 7}
PIO_KWARGS = {'sideset_enable': 0, 'offset': 0}
